# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.5-node

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v0-dependencies-{{ checksum "project.clj" }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v0-dependencies-

      - run: lein deps
      - run: npm install

      - save_cache:
          paths:
            - ~/.m2
          key: v0-dependencies-{{ checksum "project.clj" }}-{{ checksum "package.json" }}

      # Clojure (JVM)
      - run: lein test

      # ClojureScript
      - run: npx shadow-cljs compile test

workflows:
  build:
    jobs:
      - build
